version: "3"

services:
  mainDB:
    container_name: database
    image: mysql:5.7
    ports:
      - "2000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: robotics
    restart: always
    volumes:
      - .db:/var/usr/bin
  redis:
    container_name: redisStore
    image: redis
    ports:
      - "3000:6379"


volumes:
  .db: